[package]
name = "wffle"
version = "0.0.0"
edition = "2021"
resolver = "2"

[dependencies]
bytemuck = { version = "1.13", features = [ "derive" ] }
cint = "0.3.1"
hashbrown = "0.14"
mint = "0.5.9"
pollster = "0.3"
winit = "0.28"

[dependencies.wgpu]
version = "0.17"
features = ["trace", "webgl"]

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]
