[package]
name = "milun"
version = "0.0.0"
edition = "2021"
resolver = "2"

[dependencies]
bytemuck = { version = "1.13", features = [ "derive" ] }
hashbrown = "0.14.0"
pollster = "0.3"
wgpu = "0.17.0"
winit = "0.28"
