from typing import Callable, Any, Union

class Renderer:
    def __init__(self) -> None: ...
    def run(self, draw_callback: Callable[[Any, Any], None]) -> None: ...
    def set_title(self, title: str) -> None: ...
    def set_background_color(
        self, tuple: Tuple[int, int, int] | Tuple[float, float, float]
    ) -> None: ...
